name: CI-coverage

on: [pull_request, push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        php_version: ['7.3', '7.4', '8.0', '8.1' ]

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5
        with:
          php_version: "${{matrix.php_version}}"
          php_extensions: xdebug

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          php_version: "${{matrix.php_version}}"
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml.dist
          args: --coverage-clover ./coverage.xml
        env:
          XDEBUG_MODE: coverage
          TCC_EMAIL: "${{secrets.TCC_EMAIL}}"
          TCC_PASSWORD: "${{secrets.TCC_PASSWORD}}"

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=clover.xml -v